### ISSUE TITLE
OpenShift Quotas enforced für besseres Scheduling

### ISSUE THREAD

**Issue by ckaserer** [gepaplexx/docs#25]
**Problemstellung**
Wir planen eine shared cluster zu betreiben. D.h. ein Kunde bekommt einen zugesicherten Slice / Quota unseres Clusters. z.b. 8 cores 16GB Ram 500GB storage und kann über diesen frei verfügen ohne von anderen Kunden beeinträchtigt zu werden.

Durch Quota enforcment können wir ein stabileren Cluster aufbauen. Durch das enforcment muss jeder quotas verwenden. Dadurch weiß der scheduler bescheid wieviel resourcen eine app verbrauchen kann und kann sie dementsprechend am cluster platzieren.

**Aufgabenstellung**
User dürfen Quotas nicht verändern. User Workload die keine Quotas gesetzt haben dürfen nicht starten. Wir können einzelnen Namespace quotas setzen und diese enforcen. Hier müssen wir auf request und limits achten und min und max values festlegen.

**Goals**
* User müssen quotas verwenden und Kubernetes resources ohne quotas dürfen nicht starten.
* Namespace requests, limits und Limitranges mit min und max values. Min values sodass der User nicht die quotas aushebeln kann und max value damit der user nicht apps erstellt die nicht auf der unterliegenden laufen können.
* wir können neue namespaces erstellen und diese mit custom quotas / limitranges bestücken.
* Quotas und limitranges dürfen nicht vom user verändert werden.

**Definition of Done**
* Goals sind erfühlt
* Dokumentiert als github page
* "Wie kann ich einen Namespace mit quotas / limitranges erstellen"
* "Wie hebe ich die quotas / limitranges wieder auf"
* "Fully custom quota / limitranges requirements?"
* automatisierte Tests wo die quotas / limitranges überprüft werden. 
* automatisiert getestet z.b. via gitlab runner auf unserem OpenShift Cluster (jeden Wochentag)
* Dokumetation der Pipeline und wie diese eingerichtet ist. Da wir den cluster sicher noch einige male neu aufsetzen werden

**Comment by gattma** [comment]
Ähnlich wie bei #26 können auch "Resource quotas" pro Projekt vergeben werden oder direkt im Projekt-Template hinterlegt werden. Wird für ein Projekt ein Quota definiert, müssen auch im jeweiligen Deployment die entsprechenden Resource quotas angegeben werden, andernfalls wird der jeweilige Pod nicht gestartet. Ausnahmen können hier zum Beispiel für Build-Pods hinterlegt werden (Stichwort "Scopes")... . Es werden die verbrauchten Resourcen aller Pods eines Projektes zusammengefasst. Dieser Wert darf den im Quota hinterlegten Wert nicht übersteigen.
siehe https://docs.openshift.com/container-platform/4.6/applications/quotas/quotas-setting-per-project.html 

2ter Ansatz: "limit ranges". Im Unterschied zu "resource quotas" können limit ranges bis auf Pod- und Containerebene definiert werden. Zusätzlich können default-Werte vergeben werden. siehe https://docs.openshift.com/container-platform/4.6/nodes/clusters/nodes-cluster-limit-ranges.html
