### ISSUE TITLE
Network Isolation von Namespaces

### ISSUE THREAD

**Issue by ckaserer** [gepaplexx/docs#26]
**Problemstellung**
Kunde wünscht Isolation von Produktion zu Entwicklungsumgebungen und zu anderen Kunden. 

**Aufgabenstellung**
Neue Namespace können wir automatisiert mit isolieren. 
Diese Isolation kann der Kunde nicht selber aufheben. D.h. er hat keine rechte diese zu verändern.
Wir können Isolation auf namespace ebene individuell gestalten. D.h nicht alle Isolations auf einmal mangen. Kein großer on / off switch für den cluster, sondern individuell für namespace.

**Goals**
* Wie isolieren wir namespace und warum haben wir uns für den Modus entschieden -> DOKU!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
* Wir können automatisiert einen Namespace isolieren und wieder freigeben.
* Kunde darf isaltion nicht aufheben
* Granulare isolation möglichkeiten
* By Default enable isolation

**Definition of Done**
* Goals sind erfüllt
* Dokumentiert als github page
    * "Wie kann ich einen Namespace isolieren"
    * "Wie hebe ich die isolation wieder auf"
    * "Wie kann ich zwei namespace zusammenschließen, sodass sie miteinander kommunizieren können"
    * "Fully custom isolation requirements?"
* automatisierte Tests wo die Isolation überprüft wird. z.b. 2 Pods (jeder in einem namespace) die mit einander kommunizien und nach einrichten der isolation kommunikation unterbunden ist. Kunden "user" kann isolation nicht löschen / ändern (z.b. ansible, molecule)
* automatisiert getestet z.b. via gitlab runner auf unserem OpenShift Cluster (jeden Wochentag)
* Dokumetation der Pipeline und wie diese Eingerichtet ist. Da wir den cluster sicher noch einige male neu aufsetzen werden

**Comment by gattma** [comment]
3 mögliche Varianten:

Variante 1: für jedes Projekt "Network Policies" definieren. siehe https://github.com/gepaplexx/gp-network-isolation/tree/main/policies/manually und https://docs.openshift.com/container-platform/4.6/networking/network_policy/multitenant-network-policy.html
Variante 2: Ein eigenes Template für ein Openshift-Projekt anlegen. siehe https://github.com/gepaplexx/gp-network-isolation/tree/main/policies/automatic und https://docs.openshift.com/container-platform/4.6/networking/network_policy/default-network-policy.html
Variante 3: Den Modus von OpenShift SDN von "network policy" auf "multitenant" ändern. siehe https://docs.openshift.com/container-platform/4.6/networking/openshift_sdn/about-openshift-sdn.html
